# Generated by Django 5.1.6 on 2025-03-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test1', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
            ],
        ),
    ]
