# Generated by Django 5.1.6 on 2025-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Librarians', 'Librarians'), ('Member', 'Member')], default='Member', max_length=10),
        ),
    ]
