# Generated by Django 5.1.6 on 2025-02-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
    ]
