# Generated by Django 5.2.3 on 2025-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denver', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('song_file', models.FileField(upload_to='blog_images/')),
            ],
        ),
    ]
