# Generated by Django 5.2.3 on 2025-10-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denver', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='concert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='denver.concert'),
            preserve_default=False,
        ),
    ]
